---
development:
  cloud_name: ht3ikzvcb
  api_key: '358437867533733'
  api_secret: g1GUxE3auoq1UtHYf2jrVB63yM4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ht3ikzvcb
  api_key: '358437867533733'
  api_secret: g1GUxE3auoq1UtHYf2jrVB63yM4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ht3ikzvcb
  api_key: '358437867533733'
  api_secret: g1GUxE3auoq1UtHYf2jrVB63yM4
  enhance_image_tag: true
  static_image_support: false
